### ISSUE TITLE
:D share the source code captain?even the teamviewer...

### ISSUE THREAD

**Issue by YellowBlueBuzz** [uknowsec/SharpDecryptPwd#2]
thanks a lot!

**Comment by blacklat** [comment]
he will not share the code because he is a fucking idiot that uses github (developers open source community) to host their malware as binary

**Comment by uknowsec** [comment]
> he will not share the code because he is a fucking idiot that uses github (developers open source community) to host their malware as binary

Are you kidding me? Don't you know .Net program can be decompiled directly with dnspy or ilspy? Besides, do you have any evidence that this is malware?

**Comment by uknowsec** [comment]
> thanks a lot!

You can decompile to get the source code or follow another friend's project:https://github.com/RcoIl/SharpDecryptPwd
